run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - gosec
    - misspell
    - revive
    - whitespace

linters-settings:
  gosec:
    excludes:
      - G602  # Allow slice index out of range

issues:
  exclude:
    - G115  # Integer overflow conversion
    - G404  # Weak random number generator
  exclude-rules:
    # Exclude examples directory from linting
    - path: examples/
      linters:
        - gosec
        - revive

output:
  formats:
    - format: colored-line-number
